const storeLogos: Record<string, any> = {
  aldi: require("../../assets/StoresLogos/aldi.png"),
  lidl: require("../../assets/StoresLogos/lidl.png"),
  walmart: require("../../assets/StoresLogos/walmart.png"),
  hmart: require("../../assets/StoresLogos/hmart.png"),
  talpa: require("../../assets/StoresLogos/talpa.png"),
  traderjoes: require("../../assets/StoresLogos/traderjoes.png"),
  wholefoods: require("../../assets/StoresLogos/wholefoods.png"),
  kroger: require("../../assets/StoresLogos/kroger.png"),
  acmemarket: require("../../assets/StoresLogos/acmemarket.png"),
  albertsons: require("../../assets/StoresLogos/albertsons.png"),
  foodlion: require("../../assets/StoresLogos/foodlion.png"),
  fredmeyer: require("../../assets/StoresLogos/fredmeyer.png"),
  frys: require("../../assets/StoresLogos/frys.png"),
  giantfood: require("../../assets/StoresLogos/giantfood.png"),
  heb: require("../../assets/StoresLogos/h-e-b.png"),
  hannaford: require("../../assets/StoresLogos/hannaford.png"),
  ingles: require("../../assets/StoresLogos/ingles.png"),
  jewelosco: require("../../assets/StoresLogos/jewel-osco.png"),
  kingsoopers: require("../../assets/StoresLogos/kingsoopers.png"),
  meijer: require("../../assets/StoresLogos/meijer.png"),
  pigglywiggly: require("../../assets/StoresLogos/pigglywiggly.png"),
  publix: require("../../assets/StoresLogos/publix.png"),
  ralphs: require("../../assets/StoresLogos/ralphs.png"),
  rouses: require("../../assets/StoresLogos/rouses.png"),
  safeway: require("../../assets/StoresLogos/safeway.png"),
  shoprite: require("../../assets/StoresLogos/shoprite.png"),
  stopandshop: require("../../assets/StoresLogos/stopandshop.png"),
};

export default storeLogos;
